# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agenc < Formula
  desc "AgenC - Agent orchestration system"
  homepage "https://github.com/mieubrisse/agenc"
  version "0.11.0"
  license "AGPL-3.0"

  depends_on "fzf"
  depends_on "gh"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mieubrisse/agenc/releases/download/v0.11.0/agenc_0.11.0_darwin_amd64.tar.gz"
      sha256 "77f657619ab71dd16500372e03f1e300fe73606a6613b4ad854da6ffd0fdfdf1"

      define_method(:install) do
        bin.install "agenc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mieubrisse/agenc/releases/download/v0.11.0/agenc_0.11.0_darwin_arm64.tar.gz"
      sha256 "12c6945815ec4e7fa1f192e96dc5408ee828a36b20ff1ddf45994e4906e8c37e"

      define_method(:install) do
        bin.install "agenc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mieubrisse/agenc/releases/download/v0.11.0/agenc_0.11.0_linux_amd64.tar.gz"
      sha256 "d0182a55461c2e2135d9e7061c93235fb5d3acfa3302bb4e3e8d7adcfd098921"
      define_method(:install) do
        bin.install "agenc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mieubrisse/agenc/releases/download/v0.11.0/agenc_0.11.0_linux_arm64.tar.gz"
      sha256 "71e05597775958910ffcfaafba8e0b557184647cb11883c5b21359a6386a1ac0"
      define_method(:install) do
        bin.install "agenc"
      end
    end
  end

  def caveats
    <<~EOS
      🚨 If the AgenC server is running, it is still using the old version.
      The server will auto-restart on your next `agenc` CLI command, or you
      can restart it now:

        agenc server restart
    EOS
  end

  test do
    system "#{bin}/agenc", "--version"
  end
end
