# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agenc < Formula
  desc "AgenC - Agent orchestration system"
  homepage "https://github.com/mieubrisse/agenc"
  version "0.6.0"
  license "AGPL-3.0"

  depends_on "fzf"
  depends_on "gh"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mieubrisse/agenc/releases/download/v0.6.0/agenc_0.6.0_darwin_amd64.tar.gz"
      sha256 "481eb94c95e33b04bd478394d59896511020c3ed163d0f0c7cd983d0dda02850"

      define_method(:install) do
        bin.install "agenc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mieubrisse/agenc/releases/download/v0.6.0/agenc_0.6.0_darwin_arm64.tar.gz"
      sha256 "8378277bbedb233bb28ea4c89ac135068c84c17ad1a198d071c58cb6476c52aa"

      define_method(:install) do
        bin.install "agenc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mieubrisse/agenc/releases/download/v0.6.0/agenc_0.6.0_linux_amd64.tar.gz"
      sha256 "f78c9d0bd13433a713e9d63adeccbd819aa2bec68cc10346c5fb7dbad4e61c61"
      define_method(:install) do
        bin.install "agenc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mieubrisse/agenc/releases/download/v0.6.0/agenc_0.6.0_linux_arm64.tar.gz"
      sha256 "2b05911123972f9dbd674da1e09a189bfaa272e18318ac4cc5d9283c9446fda8"
      define_method(:install) do
        bin.install "agenc"
      end
    end
  end

  test do
    system "#{bin}/agenc", "--version"
  end
end
