# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agenc < Formula
  desc "AgenC - Agent orchestration system"
  homepage "https://github.com/mieubrisse/agenc"
  version "0.5.1"
  license "AGPL-3.0"

  depends_on "fzf"
  depends_on "gh"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mieubrisse/agenc/releases/download/v0.5.1/agenc_0.5.1_darwin_amd64.tar.gz"
      sha256 "c8e92d6462c7eff65a99fd445f3d28478946f1e33d3f68a0309bb149dd972a00"

      def install
        bin.install "agenc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mieubrisse/agenc/releases/download/v0.5.1/agenc_0.5.1_darwin_arm64.tar.gz"
      sha256 "d8992fa335cd76c69839607fe5c2d931fb0156f0ccbf45d5d0a3155b812374c4"

      def install
        bin.install "agenc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mieubrisse/agenc/releases/download/v0.5.1/agenc_0.5.1_linux_amd64.tar.gz"
      sha256 "2717c34c89486872d771d102e87aff23e9dc16c7eb2bbcabd1ce34b2ae070d0f"
      def install
        bin.install "agenc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mieubrisse/agenc/releases/download/v0.5.1/agenc_0.5.1_linux_arm64.tar.gz"
      sha256 "c2124c9fb9178ca7af2b74f1ba09a2197c10ac40a6a68f5133d6aa2ca5d7d60c"
      def install
        bin.install "agenc"
      end
    end
  end

  test do
    system "#{bin}/agenc", "--version"
  end
end
